# grafana/provisioning/datasources/prometheus.yaml
apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      uid: prometheus
      # Using Docker service name
      url: http://prometheus:9090
      basicAuth: false
      isDefault: true
      version: 1
      editable: true
      jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
          httpMethod: "POST"
