# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenizer_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tokenizer_service.proto\x12\x11tokenizer_service\"\x88\x01\n\tTextInput\x12\x0c\n\x04text\x18\x01 \x01(\t\x12<\n\x08metadata\x18\x02 \x03(\x0b\x32*.tokenizer_service.TextInput.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x0bTokenOutput\x12\x0e\n\x06tokens\x18\x01 \x03(\x05\"\x8c\x01\n\nTokenInput\x12\x0e\n\x06tokens\x18\x01 \x03(\x05\x12=\n\x08metadata\x18\x02 \x03(\x0b\x32+.tokenizer_service.TokenInput.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\nTextOutput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x95\x02\n\x10TokenizerService\x12N\n\x0cprocess_text\x12\x1c.tokenizer_service.TextInput\x1a\x1e.tokenizer_service.TokenOutput\"\x00\x12P\n\x0eprocess_tokens\x12\x1d.tokenizer_service.TokenInput\x1a\x1d.tokenizer_service.TextOutput\"\x00\x12_\n\x0chealth_check\x12%.tokenizer_service.HealthCheckRequest\x1a&.tokenizer_service.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _TEXTINPUT_METADATAENTRY._options = None
  _TEXTINPUT_METADATAENTRY._serialized_options = b'8\001'
  _TOKENINPUT_METADATAENTRY._options = None
  _TOKENINPUT_METADATAENTRY._serialized_options = b'8\001'
  _globals['_TEXTINPUT']._serialized_start=47
  _globals['_TEXTINPUT']._serialized_end=183
  _globals['_TEXTINPUT_METADATAENTRY']._serialized_start=136
  _globals['_TEXTINPUT_METADATAENTRY']._serialized_end=183
  _globals['_TOKENOUTPUT']._serialized_start=185
  _globals['_TOKENOUTPUT']._serialized_end=214
  _globals['_TOKENINPUT']._serialized_start=217
  _globals['_TOKENINPUT']._serialized_end=357
  _globals['_TOKENINPUT_METADATAENTRY']._serialized_start=136
  _globals['_TOKENINPUT_METADATAENTRY']._serialized_end=183
  _globals['_TEXTOUTPUT']._serialized_start=359
  _globals['_TEXTOUTPUT']._serialized_end=385
  _globals['_HEALTHCHECKREQUEST']._serialized_start=387
  _globals['_HEALTHCHECKREQUEST']._serialized_end=407
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=409
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=446
  _globals['_TOKENIZERSERVICE']._serialized_start=449
  _globals['_TOKENIZERSERVICE']._serialized_end=726
# @@protoc_insertion_point(module_scope)
